---

name: Bandit
 
on: # yamllint disable-line rule:truthy
  push: 
    branches: [main, master]
  pull_request: 
    branches: [main, master]

jobs: 
  securitycheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code on the repo
        uses: actions/checkout@v4
      - name: Run bandit security scan
        uses: tj-actions/bandit@v5.2
        with:
          targets: "."
          severity: high
          confidence: high
 
